### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by nocmt** [felixse/FluentTerminal#206]
I normally installed the program, but nothing was displayed.
![image](https://user-images.githubusercontent.com/26828323/52859611-1e867980-3168-11e9-9a3a-fd92d74f63fe.png)

**Comment by nocmt** [comment]
I don't know how to deal with it. Please help me. thanks

**Comment by ericcornelissen** [comment]
Hi @nocmt, can you give is some more info?

- What version of Windows are you running?
- Have you been waiting for a long time?
- Does PowerShell work when you launch it normally?
- Does it work i you open a new tab using a different profile (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd>)?

**Comment by nocmt** [comment]
1.  version is 0.3.1.0
2.  yes，I waited a long time.
3.  powershell is function normally.
4.  Yes, I tried all the configurations, but they didn't work properly.

I recommend adding a log function to feed back questions.

**Comment by Luupw3d** [comment]
The same problem with Windows 10 v1809.

**Comment by Littlefisher619** [comment]
The same problem with me.
Sometimes it displayed nothing until I press ENTER to the window .
And sometimes tabs are gone. 
![2](https://user-images.githubusercontent.com/8090425/52912068-36383c00-32e7-11e9-9767-b3015e72d5e7.png)
Version 0.3.1.0 on Windows10-1809 17763.195

**Comment by wizcas** [comment]
I have the same problem. I'm with Windows 10.0.17134.590.
None of the profiles works. After creating a new tab I get a blank UI with blinking caret. Hitting keyboard won't help. All tabs have no title except the initial one. 
The window can't be opened anymore if closed. By double-clicking the icon in the tray, the window flashes and closed again very soon.

**Comment by wizcas** [comment]
> Is there anything in Event Viewer? -- Hans Kokx
> […](#)
> On February 19, 2019 10:58:12 AM "Vincent (Wizcas) Chen" ***@***.***> wrote: I have the same problem. I'm with Windows 10.0.17134.590. None of the profiles works. After creating a new tab I get a blank UI with blinking caret. Hitting keyboard won't help. All tabs have no title except the initial one. The window can't be opened anymore if closed. By double-clicking the icon in the tray, the window flashes and closed again very soon.— You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I didn't see anything noticable in the Event Viewer. What event or keyword should I look for?

**Comment by Littlefisher619** [comment]
> Is there anything in Event Viewer? -- Hans Kokx
> […](#)
> On February 19, 2019 10:58:12 AM "Vincent (Wizcas) Chen" ***@***.***> wrote: I have the same problem. I'm with Windows 10.0.17134.590. None of the profiles works. After creating a new tab I get a blank UI with blinking caret. Hitting keyboard won't help. All tabs have no title except the initial one. The window can't be opened anymore if closed. By double-clicking the icon in the tray, the window flashes and closed again very soon.— You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Nothing neither in my Event Viewer.

**Comment by wizcas** [comment]
And from today on I can't open a Fluent Terminal window anymore. The application is running as shown in the system tray, but the main window closed in a second every time I try to open/show it. Is there any application log I can review?

**Comment by wizcas** [comment]
As I noticed @Littlefisher619 and I are both using Windows in zh-cn language. Is there anything to do with the OS language?

**Comment by skipmeister123** [comment]
It's certainly possible. Would it be too much to ask that you switch the system language to en-US and see if the problem persists?

**Comment by wizcas** [comment]
> It's certainly possible. Would it be too much to ask that you switch the system language to en-US and see if the problem persists?

I'll try it later and let u know the result ;)

**Comment by NarathSpring** [comment]
> It's certainly possible. Would it be too much to ask that you switch the system language to en-US and see if the problem persists?

I've tried and still have the problem.

**Comment by wizcas** [comment]
@skipmeister123 I can't change my system language to English as it is a Chinese version I installed. Sorry.

**Comment by zhkong** [comment]
> @skipmeister123 I can't change my system language to English as it is a Chinese version I installed. Sorry.

I have switched the system language to English and the problem has been solved.My system is Chinese version too.

**Comment by skipmeister123** [comment]
Thanks for checking. At least we've narrowed the issue down.

**Comment by Tonysmark** [comment]
I got same problem, and when I open it then the terminal will shut it self up...or got nothing
![image](https://user-images.githubusercontent.com/22767695/53864683-1794ad80-4028-11e9-8943-a5594f709504.png)

**Comment by mikemaccana** [comment]
Using English (proper British English) and getting same issue.

**Comment by felixse** [comment]
With the current release? Should be fixed on master, next version will be released pretty soon

**Comment by mikemaccana** [comment]
@felixse I installed via chocolatey 24h ago, I'm not sure if that's the current version or not (I haven't used chocolatey before and trying to find out via `choco list` freezes)

**Comment by mikemaccana** [comment]
Wait got the version: issue is occurring with `fluent-terminal 0.3.1.0`

**Comment by JacobMillward** [comment]
I'm still getting this issue. Installed via the bundled installer on V4.0.0.

**Comment by felixse** [comment]
Ah damnit. Can you [activate debug logging](https://github.com/felixse/FluentTerminal/wiki/Logging#activate-debug-logging) and provide some logs?

**Comment by JacobMillward** [comment]
```2019-03-24 19:52:42.098 +00:00 [INF] Initialized
2019-03-24 19:52:42.107 +00:00 [DBG] Created ApplicationViewAdapter for ApplicationView with Id: [-788675]
2019-03-24 19:52:44.148 +00:00 [DBG] WebView navigation completed. Target: ["ms-appx-web://53621fsapps.fluentterminal/Client/index.html"]
2019-03-24 19:52:44.230 +00:00 [DBG] Received GetAvailablePortResponse: [{"Port":49151,"$type":"GetAvailablePortResponse"}]
2019-03-24 19:52:44.236 +00:00 [INF] Server started at ws://127.0.0.1:49151 (actual port 49151)
2019-03-24 19:52:44.237 +00:00 [DBG] WebSocketServer started. Calling connectToWebSocket() now.
2019-03-24 19:52:44.247 +00:00 [DBG] WebSocket open
2019-03-24 19:52:44.248 +00:00 [DBG] Sending CreateTerminalRequest: [{"Id":0,"Size":{"Columns":165,"Rows":54,"$type":"TerminalSize"},"Profile":{"Id":"813f2298-210a-481a-bdbf-c17bc637a3e2","PreInstalled":true,"Name":"Powershell","Arguments":"","Location":"C:\\windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe","WorkingDirectory":"","TabThemeId":0,"LineEndingTranslation":"DoNotModify","TerminalThemeId":"00000000-0000-0000-0000-000000000000","KeyBindings":[{"Command":"813f2298-210a-481a-bdbf-c17bc637a3e2","Key":49,"Ctrl":true,"Alt":true,"Shift":false,"Meta":false,"$type":"KeyBinding"}],"$type":"ShellProfile"},"SessionType":"WinPty","$type":"CreateTerminalRequest"}]
2019-03-24 19:52:44.499 +00:00 [DBG] Received CreateTerminalResponse: [{"Success":false,"Error":"System.ArgumentException: Item has already been added. Key in dictionary: 'TERM'  Key being added: 'TERM'\r\n   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)\r\n   at FluentTerminal.SystemTray.Services.TerminalsManager.GetDefaultEnvironmentVariableString()\r\n   at FluentTerminal.SystemTray.Services.WinPty.WinPtySession.Start(CreateTerminalRequest request, TerminalsManager terminalsManager)\r\n   at FluentTerminal.SystemTray.Services.TerminalsManager.CreateTerminal(CreateTerminalRequest request)","ShellExecutableName":null,"$type":"CreateTerminalResponse"}]
2019-03-24 19:52:52.385 +00:00 [DBG] Sending TerminalExitedRequest: [{"TerminalId":0,"$type":"TerminalExitedRequest"}]
```

That's the log.

**Comment by felixse** [comment]
Looks like you already have an environment variable 'TERM'. It should work if you remove it. I will add some handling for this in the next version.

**Comment by MinchinWeb** [comment]
Ran into this same issue. v0.4.0.0 installed via Chocolatey. Nothing displayed in the main window if the `TERM` environmental variable was set, but started working when unset.

**Comment by mikemaccana** [comment]
Just wanted to echo what @felixse said - Fluent Terminal, after failing, started working again, on a different reboot, I suspect the difference is that TERM may have been set (perhaps by another terminal app).

**Comment by jhnhnck** [comment]
Can also confirm that the crash is caused by TERM environment variable being set. I had TERM="xterm-256color" set as a system variable (in Windows) previously and after removing it, the terminal session it no longer crashes.

Crash seems to be caused by an unhandled ArgumentException on line 111 of [TerminalsManager.cs](/felixse/FluentTerminal/blob/54a9d7ce0d5a383208e33c2bcee90454f06a2f43/FluentTerminal.SystemTray/Services/TerminalsManager.cs#L110-L113).

Looks like the easiest solution is just to check if a variable is set beforehand and either skipping over it or just deleting it (by setting to null first) before setting it to the correct value.

Output from the debug log file:
```
2019-03-27 12:57:53.638 -04:00 [DBG] Received CreateTerminalRequest: [{"Id":0,"Size":{"Columns":108,"Rows":36,"$type":"TerminalSize"},"Profile":{"Id":"ab942a61-7673-4755-9bd8-765aff91d9a3","PreInstalled":true,"Name":"CMD","Arguments":"","Location":"C:\\Windows\\System32\\cmd.exe","WorkingDirectory":"","TabThemeId":0,"LineEndingTranslation":"DoNotModify","TerminalThemeId":"00000000-0000-0000-0000-000000000000","KeyBindings":[{"Command":"ab942a61-7673-4755-9bd8-765aff91d9a3","Key":50,"Ctrl":true,"Alt":true,"Shift":false,"Meta":false,"$type":"KeyBinding"}],"$type":"ShellProfile"},"SessionType":"WinPty","$type":"CreateTerminalRequest"}]
2019-03-27 12:57:53.704 -04:00 [DBG] Sending CreateTerminalResponse: [{"Success":false,"Error":"System.ArgumentException: Item has already been added. Key in dictionary: 'TERM'  Key being added: 'TERM'\r\n   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)\r\n   at FluentTerminal.SystemTray.Services.TerminalsManager.GetDefaultEnvironmentVariableString()\r\n   at FluentTerminal.SystemTray.Services.WinPty.WinPtySession.Start(CreateTerminalRequest request, TerminalsManager terminalsManager)\r\n   at FluentTerminal.SystemTray.Services.TerminalsManager.CreateTerminal(CreateTerminalRequest request)","ShellExecutableName":null,"$type":"CreateTerminalResponse"}]
```

**Comment by felixse** [comment]
Anybody still having issues on 0.4.1.0?

**Comment by jhnhnck** [comment]
I'm no longer getting crashes on launch with v0.4.1.0.
OS: *Windows 10 Pro x64 (Build 18362.1)*

**Comment by Luupw3d** [comment]
It looks like it's been fixed.

**Comment by wizcas** [comment]
It works fine now on my machine. Thanks!

**Comment by mikemaccana** [comment]
All good here too.

**Comment by IzaiahSun** [comment]
The latest version 0.4.1.0 doesn't work properly on my computer. When I open this application, a gets a window like this 
![image](https://user-images.githubusercontent.com/34444372/55272322-eab97a80-52f5-11e9-8022-d250fcebd21e.png). My windows version is 1809 17763.379.

**Comment by felixse** [comment]
Can you [activate debug logging](https://github.com/felixse/FluentTerminal/wiki/Logging#activate-debug-logging) and provide some logs?

**Comment by IzaiahSun** [comment]
I opened it twice, log files are the following.
```
2019-03-30 20:30:31.128 +08:00 [INF] Initialized
2019-03-30 20:30:31.136 +08:00 [DBG] Created ApplicationViewAdapter for ApplicationView with Id: [-134337]
2019-03-30 20:30:33.855 +08:00 [DBG] WebView navigation completed. Target: ["ms-appx-web://53621fsapps.fluentterminal/Client/index.html"]
2019-03-30 20:30:33.974 +08:00 [DBG] Received GetAvailablePortResponse: [{"Port":49151,"$type":"GetAvailablePortResponse"}]
2019-03-30 20:30:33.993 +08:00 [INF] Server started at ws://127.0.0.1:49151 (actual port 49151)
2019-03-30 20:30:33.995 +08:00 [DBG] WebSocketServer started. Calling connectToWebSocket() now.
2019-03-30 20:30:34.069 +08:00 [ERR] Socket error: {}
2019-03-30 20:30:34.069 +08:00 [ERR] Socket closed: {}
2019-03-30 20:33:12.252 +08:00 [INF] Initialized
2019-03-30 20:33:12.258 +08:00 [DBG] Created ApplicationViewAdapter for ApplicationView with Id: [-593115]
2019-03-30 20:33:13.520 +08:00 [DBG] WebView navigation completed. Target: ["ms-appx-web://53621fsapps.fluentterminal/Client/index.html"]
2019-03-30 20:33:13.611 +08:00 [DBG] Received GetAvailablePortResponse: [{"Port":49152,"$type":"GetAvailablePortResponse"}]
2019-03-30 20:33:13.629 +08:00 [INF] Server started at ws://127.0.0.1:49152 (actual port 49152)
2019-03-30 20:33:13.629 +08:00 [DBG] WebSocketServer started. Calling connectToWebSocket() now.
2019-03-30 20:33:13.649 +08:00 [ERR] Socket error: {}
2019-03-30 20:33:13.649 +08:00 [ERR] Socket closed: {}
```

**Comment by fa1segod** [comment]
```
2019-03-31 20:57:11.422 +08:00 [INF] Initialized
2019-03-31 20:57:11.422 +08:00 [DBG] Created ApplicationViewAdapter for ApplicationView with Id: [-394369]
2019-03-31 20:57:12.396 +08:00 [DBG] WebView navigation completed. Target: ["ms-appx-web://53621fsapps.fluentterminal/Client/index.html"]
2019-03-31 20:57:12.504 +08:00 [DBG] Received GetAvailablePortResponse: [{"Port":49151,"$type":"GetAvailablePortResponse"}]
2019-03-31 20:57:12.511 +08:00 [INF] Server started at ws://127.0.0.1:49151 (actual port 49151)
2019-03-31 20:57:12.511 +08:00 [DBG] WebSocketServer started. Calling connectToWebSocket() now.
2019-03-31 20:57:12.521 +08:00 [ERR] Socket error: {}
2019-03-31 20:57:12.521 +08:00 [ERR] Socket closed: {}
```
Same problem, FT 0.4.1.0, winver 1903(18356.16).

**Comment by nicohouillon** [comment]
I keep running into those issues with fluent terminal 7.1to 7.4 ... was there any fix coming ? 
very frustrating to not know when the terminal will either keep running or just crash ... 
My case is mostly running WSL2 in a tab, then after a while (very random, could be seconds or hours) it won't do anything and any new tab remains blank .
windows 20h2

**Comment by XTJ-Nya** [comment]
<img width="1200" height="932" alt="Image" src="https://github.com/user-attachments/assets/47e9267e-a7b5-4bd8-8617-85613e18bb50" /> Stuck in this interface
I encountered the same problem, but I set the `TERM` environment variable.
